[package]
name = "rustbin"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
futures = { version = "0.3", default-features = false }
bytes = "1.9"
short-uuid = "0.1.4"
